
project_id = "haerhfrlzkvkmzllxpvu"

[functions.streaming-availability-deepseek]
verify_jwt = false

[functions.streaming-availability-gemini]
verify_jwt = false

[functions.get-ai-recommendations]
verify_jwt = false

[functions.watchmode-availability]
verify_jwt = false

[functions.watchmode-title-details]
verify_jwt = false

[functions.watchmode-title-search]
verify_jwt = false

[functions.streaming-availability]
verify_jwt = false
