#!/usr/bin/env node
/**
 * Convert a Supabase (PostgreSQL) plain-text dump into an SQL file
 * importable into Cloudflare D1.
 *
 * Usage:
 *   node scripts/supabase-to-d1.mjs path/to/dump.sql > import.sql
 *   npx wrangler d1 execute moviefinder --remote --file=import.sql
 *
 * Handles the `COPY <table> (cols) FROM stdin;` blocks of pg_dump.
 * Imports: auth.users (-> user + account rows) and the public app
 * tables. Passwords from Supabase are bcrypt hashes that cannot be
 * verified by the Worker — imported users keep their account but must
 * reset their password ("password" column keeps the bcrypt hash with
 * a "bcrypt:" prefix so it never validates and can be audited).
 */

import { readFileSync } from "node:fs";

const dumpPath = process.argv[2];
if (!dumpPath) {
  console.error("Usage: node scripts/supabase-to-d1.mjs <dump.sql>");
  process.exit(1);
}

const dump = readFileSync(dumpPath, "utf8");

/** Parse all COPY blocks into { 'schema.table': { columns, rows } } */
function parseCopyBlocks(sql) {
  const blocks = {};
  const lines = sql.split("\n");
  let current = null;

  for (const line of lines) {
    if (current === null) {
      const m = line.match(/^COPY\s+([\w".]+)\s*\(([^)]*)\)\s+FROM\s+stdin;/i);
      if (m) {
        const table = m[1].replace(/"/g, "");
        const columns = m[2].split(",").map(c => c.trim().replace(/"/g, ""));
        current = { table, columns, rows: [] };
      }
      continue;
    }
    if (line === "\\.") {
      blocks[current.table] = { columns: current.columns, rows: current.rows };
      current = null;
      continue;
    }
    current.rows.push(parseCopyRow(line));
  }
  return blocks;
}

/** Decode one tab-separated COPY row (handles \N, \t, \n, \\ escapes) */
function parseCopyRow(line) {
  const fields = [];
  let field = "";
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === "\t") {
      fields.push(field);
      field = "";
    } else if (ch === "\\") {
      const next = line[++i];
      if (next === "N" && field === "" && (line[i + 1] === "\t" || i + 1 === line.length)) {
        field = null;
        fields.push(field);
        field = "";
        i++; // skip the tab
      } else if (next === "t") field += "\t";
      else if (next === "n") field += "\n";
      else if (next === "r") field += "\r";
      else if (next === "\\") field += "\\";
      else field += next ?? "";
    } else {
      field += ch;
    }
  }
  fields.push(field);
  return fields;
}

const sqlString = (v) => v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const toEpochMs = (v) => {
  if (v === null || v === undefined || v === "") return "NULL";
  const t = Date.parse(v);
  return Number.isNaN(t) ? "NULL" : String(t);
};

function rowsAsObjects(block) {
  if (!block) return [];
  return block.rows.map(row => Object.fromEntries(block.columns.map((c, i) => [c, row[i] ?? null])));
}

const blocks = parseCopyBlocks(dump);
const out = [];
out.push("-- Generated by scripts/supabase-to-d1.mjs");
out.push("PRAGMA defer_foreign_keys = on;");

// ---------- auth.users -> user + account ----------
const users = rowsAsObjects(blocks["auth.users"]);
let importedUsers = 0;
for (const u of users) {
  if (!u.id || !u.email) continue;
  let name = u.email.split("@")[0];
  try {
    const meta = JSON.parse(u.raw_user_meta_data || "{}");
    name = meta.full_name || meta.name || name;
  } catch { /* keep default */ }

  const createdAt = toEpochMs(u.created_at) === "NULL" ? Date.now() : toEpochMs(u.created_at);
  const updatedAt = toEpochMs(u.updated_at) === "NULL" ? createdAt : toEpochMs(u.updated_at);
  const emailVerified = u.email_confirmed_at ? 1 : 0;

  out.push(
    `INSERT OR IGNORE INTO user (id, name, email, email_verified, image, created_at, updated_at) VALUES (` +
    `${sqlString(u.id)}, ${sqlString(name)}, ${sqlString(u.email.toLowerCase())}, ${emailVerified}, NULL, ${createdAt}, ${updatedAt});`
  );
  // bcrypt hash kept with prefix — never validates against PBKDF2 verify,
  // so the user must use password reset; the original hash stays auditable.
  const password = u.encrypted_password ? `bcrypt:${u.encrypted_password}` : null;
  out.push(
    `INSERT OR IGNORE INTO account (id, account_id, provider_id, user_id, password, created_at, updated_at) VALUES (` +
    `${sqlString(crypto.randomUUID())}, ${sqlString(u.id)}, 'credential', ${sqlString(u.id)}, ${sqlString(password)}, ${createdAt}, ${updatedAt});`
  );
  importedUsers++;
}

// ---------- app tables ----------
const tableSpecs = [
  {
    pg: "public.user_streaming_preferences", d1: "user_streaming_preferences",
    map: r => [sqlString(r.id), sqlString(r.user_id), sqlString(r.service_id), toEpochMs(r.created_at)],
    cols: "(id, user_id, service_id, created_at)",
  },
  {
    pg: "public.favorite_creators", d1: "favorite_creators",
    map: r => [sqlString(r.id), sqlString(r.user_id), sqlString(r.name), sqlString(r.role), r.tmdb_person_id ?? 0, toEpochMs(r.created_at)],
    cols: "(id, user_id, name, role, tmdb_person_id, created_at)",
  },
  {
    pg: "public.watched_movies", d1: "watched_movies",
    map: r => [sqlString(r.id), sqlString(r.user_id), r.tmdb_id, sqlString(r.title ?? ""), r.rating ?? "NULL", toEpochMs(r.watched_at), toEpochMs(r.created_at)],
    cols: "(id, user_id, tmdb_id, title, rating, watched_at, created_at)",
  },
  {
    pg: "public.saved_movies", d1: "saved_movies",
    map: r => [sqlString(r.id), sqlString(r.user_id), r.tmdb_id, sqlString(r.title ?? ""), sqlString(r.poster_path), toEpochMs(r.created_at)],
    cols: "(id, user_id, tmdb_id, title, poster_path, created_at)",
  },
  {
    pg: "public.quiz_history", d1: "quiz_history",
    map: r => [sqlString(r.id), sqlString(r.user_id), sqlString(r.answers ?? "[]"), toEpochMs(r.created_at)],
    cols: "(id, user_id, answers, created_at)",
  },
  {
    pg: "public.quiz_groups", d1: "quiz_groups",
    map: r => [sqlString(r.id), sqlString(r.name), sqlString(r.created_by), toEpochMs(r.created_at)],
    cols: "(id, name, created_by, created_at)",
  },
];

const counts = { users: importedUsers };
for (const spec of tableSpecs) {
  const rows = rowsAsObjects(blocks[spec.pg]);
  counts[spec.d1] = rows.length;
  for (const r of rows) {
    out.push(`INSERT OR IGNORE INTO ${spec.d1} ${spec.cols} VALUES (${spec.map(r).join(", ")});`);
  }
}

out.push("PRAGMA defer_foreign_keys = off;");
console.log(out.join("\n"));
console.error("Imported row counts:", JSON.stringify(counts, null, 2));
