// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haerhfrlzkvkmzllxpvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZXJoZnJsemt2a216bGx4cHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2Mjc1MzAsImV4cCI6MjA1MjIwMzUzMH0.ZBadCsrPzxAwZ41jwpb3Lgr2uOyV3yQMTd68r7tQRPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);