// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjnpzjhyegtdqwmxeeob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbnB6amh5ZWd0ZHF3bXhlZW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NjYxNzMsImV4cCI6MjA4NzM0MjE3M30.3njx5IkjbtToG8aqlRlO_KefHFZYL1fl2T3D2L751A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});